name: comments
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

flutter_intl:
  main_locale: en
  enabled: true

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  retrofit: ^4.6.0
  flutter_riverpod: ^2.6.1
  json_serializable: ^6.10.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  loggy: ^2.0.3
  flutter_loggy_dio: ^3.1.0
  either_dart: ^1.0.0
  flutter_loggy: ^2.0.3+1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  intl_utils: ^2.8.11
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0

  # GitHub dependency
  q_ui_components:
    git:
      url: https://github.com/MPasara/QUiComponents.git
  toastification: ^3.0.3
  package_info_plus: ^8.3.0
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  retrofit_generator: ^10.0.0
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  image: "assets/images/comment.png"
  color: "#FFFFFF"
  color_dark: "#121212"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
